[project]
name = "hanzihua"
version = "0.1.1"
description = "A picture frame with an ePaper display showing a Chinese word per day"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3",
    "dragonmapper",
    "pillow",
    "requests",
]

[project.optional-dependencies]
dev = [
    "boto3-stubs",
    "mypy",
    "pylint",
    "types-requests",
]
display = [
    "gpiozero",
    "spidev",
]
